backend:
  name: git-gateway
  branch: master
media_folder: "images/uploads"
public_folder: "/uploads"
collections:
  - name: posts
    label: Posts
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Category, name: category, widget: string }
      - { label: Title, name: title, widget: string }
      - { label: Description, name: deck, widget: text }
      - { label: Image, name: image, widget: image }
      - { label: Body, name: body, widget: markdown }
    filter:
      field: category
      value: electronics
